version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks: 
      - public

  backend:
    build: "backend"
    ports:
      - "8090:8090"
    networks: 
      - public

networks:
  public: